apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-catalog-content-1.0.0
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ms-catalog-content
        image: clagosu/ms-catalog-content-clase:latest
