name: CI


on:
  push:
  workflow_dispatch:
  
permissions: write-all

jobs:

  SAST:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: none
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java-kotlin"

  SCA:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mvn package

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'ms-catalog-content'
          path: '.'
          format: 'HTML'
          args: >
            --disableCentral
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with: 
          path: ${{github.workspace}}/reports
  
  Docker-build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASS_DOCKER }}

      - name: Docker build
        run: |
          docker build --tag clagosu/ms-catalog-content-clase:latest .

      - name: Docker push
        run: |
          docker push clagosu/ms-catalog-content-clase:latest

          
      

        
          
      
