name: CI


on:
  push:
  workflow_dispatch:
  
permissions: write-all

jobs:

  SAST:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: OWASP ZAP Scan
        shell: powershell
        working-directory: C:\Program Files\ZAP\Zed Attack Proxy
        run: |
           & "C:\Program Files\ZAP\Zed Attack Proxy\zap.bat" -cmd -openapifile "swagger.yaml" -openapitargeturl "http://localhost:8080"  -quickout "C:\Users\clago\OneDrive\reporte113.html"

      
      

        
          
      
